[tool.poetry]
name = "kosten-bot"
version = "0.1.0"
description = ""
authors = ["Maksim Vikhrov <maxvihr@yandex.ru>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "3.12.0"
aiogram = "^3.26.0"
sqlalchemy = "^2.0.48"
alembic = "^1.18.4"
asyncpg = "^0.31.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.19.1"
ruff = "^0.15.4"

[tool.ruff]
line-length = 80
